remote_theme: thuhcsi/slate
title: ZERO-SHOT SPEAKER ADAPTATION TEXT-TO-SPEECH WITH CONTENT-DEPENDENT FINE-GRAINED SPEAKER EMBEDDING
description: submitted to ICASSP 2022.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
